#!/bin/sh
#
# start postgresql
#

POSTGRES_DBDIR=/mnt/data/pgsql
POSTGRES_USER=postgres

umask 077

start() {
    if [ ! -f $POSTGRES_DBDIR/PG_VERSION ]; then
        echo "Initializing postgresql database..."
        mkdir -p $POSTGRES_DBDIR
        chmod 700 $POSTGRES_DBDIR
        su - $POSTGRES_USER -c "/usr/bin/pg_ctl initdb -D $POSTGRES_DBDIR"
        echo "done"
    fi

    chown -R $POSTGRES_USER.$POSTGRES_USER $POSTGRES_DBDIR

    printf "Starting postgresql: "
    su - postgres -c "/usr/bin/pg_ctl start -w -D $POSTGRES_DBDIR -l logfile"
    echo "OK"
}
stop() {
    printf "Stopping postgresql: "
    su - postgres -c "/usr/bin/pg_ctl stop -D $POSTGRES_DBDIR -m fast"
    echo "OK"
}
restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
