#!/bin/sh

PID_FILE=/var/run/ondd.pid
CACHE_PATH=/mnt/data/cache
MAIN_STORAGE=/mnt/data/downloads
EXT_STORAGE=/mnt/external

has_external() {
    mount | grep "$EXT_STORAGE" >/dev/null 2>&1
}

start() {
  [ -d /mnt/data/ondd ] || mkdir /mnt/data/ondd
  [ -d $CACHE_PATH ] || mkdir $CACHE_PATH
  [ -d $MAIN_STORAGE ] || mkdir $MAIN_STORAGE
  for storage in $MAIN_STORAGE $EXT_STORAGE; do
      chgrp data $storage
      chmod g+ws $storage
  done

  if has_external; then
    output_path=$EXT_STORAGE
  else
    output_path=$MAIN_STORAGE
  fi

  echo -n "Starting ondd: "
  start-stop-daemon -S -q -p $PID_FILE --exec /usr/sbin/ondd -- -d --pid-file $PID_FILE -c $CACHE_PATH -o $output_path
  if [ $? ]; then
    echo "OK"
  else
    echo "FAILED"
  fi
}

stop() {
  echo -n "Stopping ondd: "
  start-stop-daemon -K -q -p $PID_FILE
  [ -f $PID_FILE ] && rm $PID_FILE
  echo "OK"
}

restart() {
  stop
  /bin/sleep 1
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac

exit $?
