#!/bin/sh

PID_FILE=/var/run/ondd.pid
CACHE_PATH=/mnt/data/cache
OUTPUT_PATH=/mnt/data/downloads

start() {
  [ -d /mnt/data/ondd ] || mkdir /mnt/data/ondd
  [ -d $CACHE_PATH ] || mkdir $CACHE_PATH
  [ -d $OUTPUT_PATH ] || mkdir $OUTPUT_PATH

  echo -n "Starting ondd: "
  start-stop-daemon -S -q -p $PID_FILE --exec /usr/sbin/ondd -- -d --pid-file $PID_FILE -c $CACHE_PATH -o $OUTPUT_PATH
  if [ $? ]; then
    echo "OK"
  else
    echo "FAILED"
  fi
}

stop() {
  echo -n "Stopping ondd: "
  start-stop-daemon -K -q -p $PID_FILE
  [ -f $PID_FILE ] && rm $PID_FILE
  echo "OK"
}

restart() {
  stop
  /bin/sleep 1
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac

exit $?
