#!/bin/sh

IFACE=$1
STATE=$2
DHCP=/sbin/udhcpc
HOSTNAME=$(cat /etc/hostname)
PIDFILE=/var/run/udhcpc.${IFACE}.pid

case "$STATE" in
    up)
        if [ -f $PIDFILE ];
        then
            exit 0
        fi
        $DHCP -x hostname:$HOSTNAME -i $IFACE -p $PIDFILE -S -b
        ;;
    down)
        kill $(cat $PIDFILE)
        ;;
esac
