#!/bin/sh

usage() {
    echo "Usage: $0 PATH"
    echo
    echo "    PATH - path to kernel image"
    echo
}

fail() {
    echo "FAIL"
    echo "$1"
    exit 1
}

if [ "$USER" != "root" ]; then
    echo "This script must be run as root"
    exit 1
fi

if [ -z "$1" ]; then
    usage
    exit 1
fi

image_path=$1


echo -n "Installing new image..."
umount -f /boot  >/dev/null 2>&1  # No problem if it cannot be unmounted right now
mount /boot || fail "Failed to mount the boot partition"
mv $image_path /boot >/dev/null 2>&1 || fail "Could not install image"
sync || fail "Failed to sync i/o"
echo "DONE"
echo "Rebooting..."
umount /boot 2>&1 >/dev/null  # Not a problem if it cannot be unmounted
reboot || fail "Could not reboot. Please restart the receiver manually."
